### ISSUE TITLE
date is always in Hijri even with PickerType.JWestern

### ISSUE THREAD

**Issue by seifguizani** [AymanYassinn/HijriDatePicker#1]
Hi
First of all thank you for this effort.

I tried to use it but when I display the picker in western type (pickerType: PickerType.JWestern), dateTime.westernDate.toString() gives me the date in Hijri ! Any idea how to deal with it please ?

Even in the widget, it's displayed in Arabic

![image](https://user-images.githubusercontent.com/81054142/203144296-d88e781a-527d-4e0c-92de-bffe2ad26470.png)

Regards

**Comment by AymanYassinn** [comment]
Hello, You should try the new release we made a new widget called Global Picker its easy to use.
thanks.
